# ä¸ç”¨åœ¨æç¤ºç¬¦çš„å¼€å§‹æ¢è¡Œ
add_newline = false

# å°†æç¤ºç¬¦æ ‡å¿—ç”±â€œâ¯â€æ¢æˆâ€œâœâ€
[character]      # æ­£åœ¨é…ç½®çš„ç»„ä»¶åç§°æ˜¯â€œcharacterâ€
symbol = "âœ"     # â€œsymbolâ€å­—æ®µè¢«è®¾ç½®ä¸º "âœ"
# disabled = true
# format = "$symbol "
# success_symbol = "[âœ](bold green) "
# error_symbol = "[âœ—](bold red) "
# vicmd_symbol = "âš¡ï¸"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
